# Generated by Django 3.2.15 on 2022-09-21 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Weight (kilos)')),
                ('height_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Height (meters)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('label', models.CharField(max_length=255, verbose_name='Training label')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Training slug')),
                ('action_name', models.CharField(help_text='Training action name (step, repeat, etc.)', max_length=255, verbose_name='Action name')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_units', models.IntegerField(help_text='How many training units (steps, repeats, etc.) done during training', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Training units')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('finished_at', models.DateTimeField(verbose_name='Finished At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training.profile')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training.trainingtype')),
            ],
            options={
                'ordering': ['-finished_at', '-started_at'],
            },
        ),
    ]
