# Generated by Django 3.2.14 on 2022-07-15 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Weight (kilos)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(help_text='How many training units (steps, repeats, etc.) done during training', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Training units')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('finished_at', models.DateTimeField(verbose_name='Finished At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
